# Generated by Django 3.2.9 on 2021-12-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=6)),
                ('sala', models.CharField(max_length=5)),
                ('seccion', models.CharField(max_length=10)),
                ('sigla', models.CharField(max_length=12)),
            ],
        ),
    ]
